### ISSUE TITLE
Does this support projects?

### ISSUE THREAD

**Issue by ryan-blunden** [tumblr/SwiftCompilationPerformanceReporter#1]
Hello!

This looks excellent and I would like to use it, however I don't workspaces for most of my projects. Will this work for projects too?

**Comment by jasdev** [comment]
@ryan-blunden In its current state, SwiftCPR won't work for project files. However, this shouldn't be too hard to add 😄 I'll try to get to it this week / early next week!

**Comment by ryan-blunden** [comment]
Let me know if I can help with testing or documentation.

On Tuesday, 24 May 2016, Jasdev Singh notifications@github.com wrote:

> @ryan-blunden https://github.com/ryan-blunden In its current state,
> SwiftCPR won't work for project files. However, this shouldn't be too hard
> to add 😄 I'll try to get to it this week / early next week!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/tumblr/SwiftCompilationPerformanceReporter/issues/1#issuecomment-221015306

## 

Cheers,
Ryan

http://www.linkedin.com/in/ryanblunden
http://ryanblunden.com

**Comment by jasdev** [comment]
@ryan-blunden Finally got around to this! Some of the build steps had to change with the latest SDKs, but I updated the README accordingly. Let me know if you run into any issues and I'll re-open this 😄

**Comment by ryan-blunden** [comment]
Thanks @Jasdev! I'll give this a shot for a project I'm currently working on.
