### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by lfarah** [tumblr/SwiftCompilationPerformanceReporter#2]
<img width="586" alt="screen shot 2016-05-16 at 11 31 41 pm" src="https://cloud.githubusercontent.com/assets/6511079/15313169/66cdc83c-1bbe-11e6-90b6-b4604ae769cd.png">

Should be something like: 

> Generate automated reports for slow Swift compilation paths in specific targets

**Comment by jasdev** [comment]
Done! Thanks!
